[project]
site_name = "Dev Notes"
site_url = "https://code.lamonaca.dev/m-lamonaca/dev-notes"
site_author = "Marcello Lamonaca"
repo_url = "https://code.lamonaca.dev/m-lamonaca/dev-notes"
repo_name = "m-lamonaca/dev-notes"
copyright = "CC-BY-4.0"

docs_dir = "docs"
site_dir = "public"

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
auto_title = true
linenums = true
linenums_style = "table"
pygments_lang_class = true
line_spans = "__span"

[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]

[markdown_extensions.zensical.extensions.preview.configurations]
 targets.include = [
	"customization.md",
	"setup/extensions/*"
]

[[project.extra.social]]
icon = "fontawesome/solid/globe"
link = "https://lamonaca.dev"

[[project.extra.social]]
icon = "fontawesome/brands/mastodon"
link = "https://hachyderm.io/@m_lamonaca"

[[project.extra.social]]
icon = "fontawesome/brands/git-alt"
link = "https://code.lamonaca.dev/m-lamonaca/dev-notes"

[project.theme]
# variant = "classic"
language = "en"
features = [
	"content.code.copy",
	"content.code.select",
	"navigation.footer",
	"navigation.indexes",
	"navigation.instant",
	"navigation.instant.prefetch",
	"navigation.instant.progress",
	"navigation.path",
	"navigation.pruning",
	"navigation.sections",
	"navigation.tabs",
	"navigation.tabs.sticky",
	"navigation.top",
	"navigation.tracking",
	"search.highlight",
	"toc.follow",
]

[project.theme.font]
text = "Atkinson Hyperlegible Next"
code = "Atkinson Hyperlegible Mono"

[project.theme.icon]
logo = "fontawesome/solid/code"
repo = "fontawesome/brands/git-alt"
previous = "fontawesome/solid/angle-left"
next = "fontawesome/solid/angle-right"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "orange"
accent = "deep orange"
toggle = { icon = "material/brightness-7", name = "Switch to dark mode" }

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "orange"
accent = "deep orange"
toggle = { icon = "material/brightness-4", name = "Switch to light mode" }

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle = { icon = "material/brightness-auto", name = "Switch to light mode" }

[[project.nav]]
Containers = [
	"containers/podman.md",
	"containers/kubernetes.md"
]

[[project.nav]]
Databases = [
	"databases/redis.md",
	"databases/sql.md",
	"databases/mongo-db.md",
]

[[project.nav]]
Languages = [
	"languages/c/c.md",
	"languages/css/css.md",
	"languages/html/html.md",
	"languages/kotlin/kotlin.md",
	"languages/markdown/markdown.md",
	"languages/swift/swift.md",
	{
		Assembly = [
			"languages/assembly/intel.md",
			"languages/assembly/riscv.md"
		]
	},
	{
		Bash = [
			"languages/bash/commands.md",
			"languages/bash/scripting.md"
		]
	},
	{
		".NET" = [
			{
				"C#" = [
					"languages/dotnet/csharp/csharp.md",
					"languages/dotnet/csharp/async-await.md",
					"languages/dotnet/csharp/collections.md",
					"languages/dotnet/csharp/linq.md",
					"languages/dotnet/csharp/reactive-extensions.md",
					"languages/dotnet/csharp/tests.md"
				]
			},
			{
				"ASP.NET" = [
					"languages/dotnet/asp.net/blazor.md",
					"languages/dotnet/asp.net/filters.md",
					"languages/dotnet/asp.net/middleware.md",
					"languages/dotnet/asp.net/minimal-api.md",
					"languages/dotnet/asp.net/razor-syntax.md",
					"languages/dotnet/asp.net/signalr.md",
					"languages/dotnet/asp.net/web-forms.md"
				]
			},
			{
				Database = [
					"languages/dotnet/database/ado.net.md",
					"languages/dotnet/database/entity-framework.md"
				]
			}
		]
	},
	{
		Java = [
			"languages/java/java.md",
			"languages/java/collections.md",
			"languages/java/database.md",
			"languages/java/servlet.md",
			"languages/java/spring.md"
		]
	},
	{
		Javascript = [
			"languages/javascript/javascript.md",
			"languages/javascript/dom.md",
			"languages/javascript/events-animation.md",
			"languages/javascript/ajax.md",
			"languages/javascript/jquery.md",
			"languages/javascript/svelte.md",
			{
				React = [
					"languages/javascript/react/react.md",
					"languages/javascript/react/react-router.md",
					"languages/javascript/react/react-tests.md",
					"languages/javascript/react/redux.md",
					"languages/javascript/react/redux-tests.md"
				]
			}
		]
	},
	{
		PHP = [
			"languages/php/php.md",
			"languages/php/composer.md",
			"languages/php/database.md",
			"languages/php/dependency-injection.md",
			"languages/php/plates-templating.md",
			"languages/php/psr-7.md",
			"languages/php/tests.md",
			"languages/php/web.md",
		]
	},
	{
		Python = [
			"languages/python/python.md",
			{
				Modules = [
					"languages/python/modules/argparse.md",
					"languages/python/modules/collections.md",
					"languages/python/modules/csv.md",
					"languages/python/modules/ftplib.md",
					"languages/python/modules/itertools.md",
					"languages/python/modules/json.md",
					"languages/python/modules/logging.md",
					"languages/python/modules/shutil.md",
					"languages/python/modules/smtplib.md",
					"languages/python/modules/socket.md",
					"languages/python/modules/sqlite.md",
					"languages/python/modules/time-datetime.md",
					"languages/python/modules/unittest.md"
				]
			},
			{
				Libraries = [
					"languages/python/libraries/beautiful-soup.md",
					"languages/python/libraries/numpy.md",
					"languages/python/libraries/pandas.md",
					"languages/python/libraries/requests.md",
					"languages/python/libraries/seaborn.md",
					"languages/python/libraries/tkinter.md",
				]
			}
		]
	},
	{
		Rust = [
			"languages/rust/cargo.md",
			"languages/rust/concurrency.md",
			"languages/rust/macros.md",
			"languages/rust/rust.md",
			"languages/rust/tests.md"
		]
	},
	{
		Powershell = [
			"languages/powershell/commands.md",
			"languages/powershell/scripting.md"
		]
	}
]

[[project.nav]]
Misc = [
	"misc/graph-ql.md",
	"misc/regular-expressions.md",
	"misc/ssh.md",
	"misc/web-components.md",
	{
		VCS = [
			"misc/vcs/git.md",
			"misc/vcs/jj.md"
		]
	}
]

[[project.nav]]
Linux = [
	{
		Filesystem = [
			"linux/filesystem/file-links.md",
			"linux/filesystem/procfs.md",
			"linux/filesystem/sysfs.md"
		]
	},
	{
		Init = [
			"linux/init/systemd.md",
			"linux/init/open-rc.md",
			"linux/init/runit.md"
		]
	}
]
